### ISSUE TITLE
Cannot add middleware after an application has started

### ISSUE THREAD

**Issue by LeoBorquez** [arktronic/sd-multi#7]
found this error, in a clean installation.
I followed the steps of the tutorial, everything was going fine until I ran 

> ./run-automatic1111.sh

when the docker build finished and tried to run the UI 
![image](https://user-images.githubusercontent.com/15177945/223025212-496bb097-5c16-4d2f-a51b-fa0d3aad1a14.png)

possible solution
[web ui issue](https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/7749)

**Comment by arktronic** [comment]
Thank you for the bug report! Looks like this issue can be fixed simply by updating to latest. I'll do that shortly.
