### ISSUE TITLE
Set IP address

### ISSUE THREAD

**Issue by tkocou** [arktronic/sd-multi#8]
I installed and ran per instructions. No problems there. However, When I ran the **./run-sygil-streamlit.sh** script, the IP addresses assigned for browsing were totally random. I looked at the various build files associated with that script and have not been able to figure out how to assign the IP addresses.
As things stand, the Docker build is useless as there is no way to access it on my LAN.

Update: I checked the Docker documentation and setting up the network is fairly simple. However, which docker file needs modification so that all containers will use the same LAN subnet?

**Comment by tkocou** [comment]
Turns out that the reported IP address is bogus. 'localhost' works okay.

**Comment by arktronic** [comment]
The reported IP addresses are for an internal Docker network, which is why they don't work outside Docker. Glad you found `localhost` working 😄
